#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroAngle.h";

task main() {
	int cumulativeAngle = 0;
	while(true) {
		GyroOpen();
		nxtDisplayCenteredBigTextLine(4, "%d", cumulativeAngle);
		wait1Msec(3);
		cumulativeAngle += GyroUpdate(gyro);
	}
}
